### PR TITLE
Bring in Media Type and ACME discussion from Trust Expressions.

### PR DESCRIPTION
**Pull request by bob-beck**
Bring in Media Type and ACME discussion from Trust Expressions.

Issue: 51

### CODE REVIEW

**Comment by davidben** [comment]
Leaving this comment to link to issue #51. (`Issue: 51` doesn't work in GitHub.)

**Review by davidben — APPROVED** [review]

**Review by davidben — CHANGES_REQUESTED** [review]
Oh actually this doesn't build...
https://github.com/davidben/tls-trust-expressions/actions/runs/10101106704/job/27933936650?pr=55

**Comment by bob-beck** [comment]
Yeah I was in the middle of trying to discern the warnings from errors to fix it ;)

**Comment by davidben** [comment]
I think you need to replace "See {{Section 9 of I-D.davidben-tls-trust-expr}}." with "See {{Section 9 of ?I-D.davidben-tls-trust-expr}}".

(At least one reference needs to specify `!` for normative or `?` for informative. We've dropped the last normative use, so I guess it's just informative now.)

**Comment by bob-beck** [comment]
fun.. of course I'm just about to remove that in the next pr.. :)

**Review by davidben — APPROVED** [review]

**Pull request merged**
